// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrBsjF8UPd0_w-DG2yl0Tg4crp43BgIUg',
    appId: '1:977987831887:web:9dd29573629791be9dc23a',
    messagingSenderId: '977987831887',
    projectId: 'flutter-whatsapp-clone-dacf1',
    authDomain: 'flutter-whatsapp-clone-dacf1.firebaseapp.com',
    storageBucket: 'flutter-whatsapp-clone-dacf1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZY8onurhnCBxUzjCeJ5PomrvZ_z-8P8M',
    appId: '1:977987831887:android:8180ff8d69b1b8fa9dc23a',
    messagingSenderId: '977987831887',
    projectId: 'flutter-whatsapp-clone-dacf1',
    storageBucket: 'flutter-whatsapp-clone-dacf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKVXLlM0h7AX6lC6aBxpVi4NZoLqh4-l0',
    appId: '1:977987831887:ios:3417a3481108ebdd9dc23a',
    messagingSenderId: '977987831887',
    projectId: 'flutter-whatsapp-clone-dacf1',
    storageBucket: 'flutter-whatsapp-clone-dacf1.appspot.com',
    iosClientId: '977987831887-kgcnoab437nsc2qhkqopbalhtllclcva.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWhatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKVXLlM0h7AX6lC6aBxpVi4NZoLqh4-l0',
    appId: '1:977987831887:ios:3417a3481108ebdd9dc23a',
    messagingSenderId: '977987831887',
    projectId: 'flutter-whatsapp-clone-dacf1',
    storageBucket: 'flutter-whatsapp-clone-dacf1.appspot.com',
    iosClientId: '977987831887-kgcnoab437nsc2qhkqopbalhtllclcva.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWhatsappClone',
  );
}
